# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkTHo36fRRUHGtbDehNiPTTtK7HgVkut
"""

import numpy as np

expirys = np.linspace(5, 5, num = 1)
strikes = np.linspace(80, 100 , num = 5)
spots = np.linspace(80, 100 , num = 5)
vols = np.linspace(0.5, 0.5 , num = 1)
rs = np.linspace(0.05,0.3 , num = 3)
ds = np.linspace(0.05,0.3 , num = 3)

with open('input.csv', 'w', encoding='UTF8') as f:
  for expiry in expirys:
    for strike in strikes:
      for spot in spots:
        for vol in vols:
          for r in rs:
            for d in ds:
              f.write(f"{expiry},{strike},{spot},{vol},{r},{d}\n")

