#include "ParkMiller.hpp"
#include <iostream>
#include "Statistic.hpp"
#include "AntiThetic.hpp"
#include "Path.hpp"
#include "ExoticEngine.hpp"
#include <string>
#include <fstream>
#include <sstream>
#include <chrono>
#include <omp.h>